# config/config.yaml

model:
  name_or_path: "models/Qwen2.5-7B-Instruct"
  tokenizer_name_or_path: "models/Qwen2.5-7B-Instruct"

embeddings:
  model_name: "models/paraphrase-multilingual-MiniLM-L12-v2"

vector_store:
  index_path: "data/vector_index"

app:
  host: "127.0.0.1"
  port: 7860
